### PR TITLE
correct parameter order in log.error calls

### PR DESCRIPTION
**Pull request by santiagonoguez**
Good news is that we received uncaught exceptions in BQ
Bad news is that the detail goes first and the user friendly message goes second in log.error():
https://github.com/Rise-Vision/rise-common-electron/blob/master/logger.js#L87

so we aren't getting the relevant detail into BQ. This fixes that.

### CODE REVIEW

**Comment by andrecardoso** [comment]
Isn't it better to change in `rise-common-electron` instead?

**Comment by stulees** [comment]
@andrecardoso @santiagonoguez Can you confirm all player electron logs are formatted correctly for all logger API calls? I noticed we bumped rise-common-electron several versions higher in https://github.com/Rise-Vision/rise-player-electron/pull/50 . Just want to make sure this hasn't broken anything else.

**Comment by santiagonoguez** [comment]
@stulees I'll check, I agree that's important.

**Comment by andrecardoso** [comment]
@stulees @santiagonoguez  I checked the diff between 2.2.1 and 2.2.8 before updating and didn't find anything that could break

**Comment by santiagonoguez** [comment]
@stulees I corrected a couple of other calls with wrong parameter order.

**Pull request merged**
